env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
splash = false 

$mod = SUPER 

exec-once=waybar &
exec-once=dunst &
exec-once = bash -c "sleep 0.5 && hyprpaper --config /home/cachebag/.config/hypr/hyprpaper.conf"
exec-once=hypridle
exec-once = ~/dotfiles/scripts/wal-watch.sh &
workspace = 1, monitor:DP-2, default:true
workspace = 3, monitor:HDMI-A-1, default:true

exec-once = hyprctl dispatch workspace 1
exec-once = hyprctl dispatch focusmonitor DP-2
