decoration {

  shadow {
    enabled = true
    range = 4
    render_power = 3
    color = rgba(000000aa) 
  }

  blur {
    enabled = true
    size = 6
    passes = 3
    vibrancy = 0.15
    new_optimizations = on
    ignore_opacity = false
    xray = false
    }
}

windowrule = float 1, match:class org.nmrs.ui
windowrule {
    name = float-yazi
    match:class = wallpaper-picker
    float = on
    center = on
    size = 900 600
}

