ipc = on
splash = false

wallpaper {
    monitor = eDP-1
    path = /home/alk9fh/wallpapers/wallhaven-5ymlv9.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-5
    path = /home/alk9fh/wallpapers/wallhaven-5ymlv9.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-11
    path = /home/alk9fh/wallpapers/wallhaven-5ymlv9.png
    fit_mode = cover
}
