local mod = "SUPER"
local dsp = hl.dsp
local win = hl.dsp.window
local home = os.getenv("HOME") or ""
hl.bind(mod .. " + Return", dsp.exec_cmd("gnome-terminal --hide-menubar"))
hl.bind(mod .. " + B", dsp.exec_cmd("firefox"))
hl.bind(mod .. " + Q", win.close())
hl.bind(mod .. " + E", dsp.exec_cmd("thunar"))
hl.bind(mod .. " + A", dsp.exec_cmd(home .. "/.config/rofi/launchers/type-3/launcher.sh"))
hl.bind(mod .. " + V", win.float({ action = "toggle" }))
hl.bind(mod .. " + P", win.pseudo())
hl.bind(mod .. " + M", dsp.exit())
hl.bind(mod .. " + D", dsp.exec_cmd("chromium --app=https://chat.com --class=ChatGPT"))
hl.bind(mod .. " + I", dsp.exec_cmd("chromium --app=https://web.whatsapp.com --class=Whatsapp"))
hl.bind(mod .. " + W", dsp.exec_cmd("kitty --class wallpaper-picker " .. home .. "/.config/hypr/scripts/wallpaper.sh"))
hl.bind(mod .. " + S", dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))
hl.bind(mod .. " + O", dsp.exec_cmd("obsidian"))
hl.bind(mod .. " + Y", dsp.exec_cmd("pkill waybar; nohup waybar >/dev/null 2>&1 &"))
hl.bind(mod .. " + H", dsp.exec_cmd(home .. "/dotfiles/hyprland/scripts/toggle_blur.sh"))
hl.bind(mod .. " + P", dsp.exec_cmd(home .. "/dotfiles/scripts/power_menu.sh"))
hl.bind(mod .. " + L", dsp.exec_cmd("hyprlock"))
for i = 1, 10 do
    local key = i % 10
    hl.bind(mod .. " + " .. key, dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key, win.move({ workspace = i }))
end
hl.bind(mod .. " + CTRL + Left", dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + Right", dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + Left", dsp.focus({ direction = "left" }))
hl.bind(mod .. " + Right", dsp.focus({ direction = "right" }))
hl.bind(mod .. " + Up", dsp.focus({ direction = "up" }))
hl.bind(mod .. " + Down", dsp.focus({ direction = "down" }))
hl.bind(mod .. " + mouse:272", win.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", win.resize(), { mouse = true })
hl.bind(mod .. " + SHIFT + Left", win.resize({ x = -40, y = 0, relative = true }))
hl.bind(mod .. " + SHIFT + Right", win.resize({ x = 40, y = 0, relative = true }))
hl.bind(mod .. " + SHIFT + Up", win.resize({ x = 0, y = -40, relative = true }))
hl.bind(mod .. " + SHIFT + Down", win.resize({ x = 0, y = 40, relative = true }))
hl.bind(mod .. " + SHIFT + M", dsp.exec_cmd([[kitty sh -c "]] .. home .. [[/dotfiles/nmrs.sh"]]))
local hold = { repeating = true }
local locked = { locked = true }
hl.bind("XF86AudioRaiseVolume", dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), hold)
hl.bind("XF86AudioLowerVolume", dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), hold)
hl.bind("XF86AudioMute", dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), locked)
hl.bind("XF86AudioMicMute", dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), locked)
hl.bind("XF86MonBrightnessUp", dsp.exec_cmd("brightnessctl set 5%+"), hold)
hl.bind("XF86MonBrightnessDown", dsp.exec_cmd("brightnessctl set 5%-"), hold)
hl.bind("XF86KbdBrightnessUp", dsp.exec_cmd([[brightnessctl --device='*kbd_backlight' set 10%+]]), hold)
hl.bind("XF86KbdBrightnessDown", dsp.exec_cmd([[brightnessctl --device='*kbd_backlight' set 10%-]]), hold)
hl.bind("XF86AudioPlay", dsp.exec_cmd("playerctl play-pause"), locked)
hl.bind("XF86AudioPause", dsp.exec_cmd("playerctl play-pause"), locked)
hl.bind("XF86AudioNext", dsp.exec_cmd("playerctl next"), locked)
hl.bind("XF86AudioPrev", dsp.exec_cmd("playerctl previous"), locked)
