if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

[[ -f "$HOME/.config/zsh/secrets.zsh" ]] && source "$HOME/.config/zsh/secrets.zsh"

alias ls='ls -1 --color=auto'
alias vim='nvim'
alias copy='wl-copy'
alias disk='df -h --output=source,size,used,avail,target | grep -E "Filesystem|/dev/nvme|/dev/sd" | grep -v "/dev/nvme0n1p1"'

alias gs='git status'
alias gd='git diff'
alias gl='git log'
alias gc='git checkout'
alias gp='git pull'

bindkey -v
bindkey '^[[1;2C' forward-word
bindkey '^[[1;2D' backward-word
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS

zinit light zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

zinit light zdharma-continuum/history-search-multi-word

export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/bin/core_perl:$PATH"

[[ -f "$HOME/.local/bin/env" ]] && . "$HOME/.local/bin/env"

autoload -Uz compinit && compinit -C

if [[ $TERM_PROGRAM != "vscode" ]] && command -v fastfetch >/dev/null 2>&1; then
  fastfetch
fi

if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
else
  PROMPT='%F{blue}%~%f
%F{green}❯%f '
fi

zinit light zsh-users/zsh-syntax-highlighting
