### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

# Aliases
alias ls='ls -1 --color=auto'
alias vim='nvim'
alias copy='wl-copy'
alias free='df -h --output=source,size,used,avail,target | grep -E "Filesystem|/dev/nvme|/dev/sd" | grep -v "/dev/nvme0n1p1"'

# Set Spaceship options BEFORE loading the prompt
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname
  git           # Git section (branch, dirty, etc.)
  node          # Node.js version
  docker        # Docker context
  venv          # Python virtualenv
  exec_time     # Execution time
  line_sep
  jobs
  exit_code
  char          # Prompt character
)

SPACESHIP_GIT_SHOW=true
SPACESHIP_VENV_SHOW=true
SPACESHIP_NODE_SHOW=true
SPACESHIP_PROMPT_ADD_NEWLINE=true

bindkey -v                       # Use vi keybindings (or skip if you prefer emacs)
bindkey '^[[1;2C' forward-word   # Shift+Right = move forward one word
bindkey '^[[1;2D' backward-word  # Shift+Left  = move backward one word

bindkey '^[[1;5C' forward-word   # Ctrl+Right
bindkey '^[[1;5D' backward-word  # Ctrl+Left

# Location and size of the history file
HISTFILE=~/.zsh_history
HISTSIZE=10000           # Number of commands to keep in memory
SAVEHIST=10000           # Number of commands to write to disk

# Share history between sessions
setopt APPEND_HISTORY     # Don’t overwrite history file
setopt SHARE_HISTORY      # Share history across terminals
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY # Write after each command


zinit light denysdovhan/spaceship-prompt

# Autosuggestions (gray ghost text)
zinit light zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

# Syntax highlighting (colorful input)
zinit light zsh-users/zsh-syntax-highlighting
fpath+=~/.zfunc

# Fuzzy history search 
zinit light junegunn/fzf
zinit light zdharma-continuum/history-search-multi-word

# Run neofetch on terminal start
if [[ $TERM_PROGRAM != "vscode" ]]; then
  fastfetch
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/cachebag/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/cachebag/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/cachebag/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/cachebag/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

